name: Build APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: prayer-clock-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    
    # یہ شامل کریں build reports کے لیے
    - name: Upload Build Reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: build-reports
        path: |
          **/build/reports/
          **/build/logs/
